### ISSUE TITLE
Add support for current stable

### ISSUE THREAD

**Issue by Nef10** [hpi-swa/filetreeCI#5]
it would be nice to have a `SqueakCurrentStable`option which can be used as fallback if no smalltalk version is set

**Comment by fniephaus** [comment]
If I understand you correctly, you want to introduce a default value for `SMALLTALK`?
Or do you want an alias for the latest stable Squeak image? Something more like `SqueakLatestStable`?

**Comment by Nef10** [comment]
I would like an alias. (which e.g. can be used as fallback in travis-ci/travis-build/pull/530)
